### ISSUE TITLE
index.php

### ISSUE THREAD

**Issue by iskono** [alterebro/WeaselCMS#1]
add `<ul class="nav navbar-nav">`
in row:
`$_DATA['menu'] = '<ul>';` 
change it to 
`	$_DATA['menu'] = '<ul class="nav navbar-nav">';`

so it can work with most of templates by adding <nav> before ul
template example
example : `<ul id="nav" class="nav">`
` <nav>{{ $_CMS['menu'] }}</nav> </ul>`

**Comment by alterebro** [comment]
updated code in the recent commit 2b0ae1d  should resolve that.
