### ISSUE TITLE
uploading images 

### ISSUE THREAD

**Issue by iskono** [alterebro/WeaselCMS#2]
Fatal error: Class 'finfo' not found in C:\www\htdocs\front\v3\weasel-cms\upload.php on line 161
not working

**Comment by alterebro** [comment]
Hi @iskono ,
PHP >= 5.3 comes with the Fileinfo extension bundled (http://php.net/manual/en/fileinfo.installation.php)
please check what version your hosting is running.

Also, from the comments on that page:
*Windows users: just edit php.ini and uncomment this line:*
```
extension=php_fileinfo.dll
```
*Remember to restart Apache for new php.ini to take effect.*

**Comment by iskono** [comment]
@alterebro ,
fixed but nothing happens after uploading

**Comment by alterebro** [comment]
@iskono , check permissions on the `/files` folder, the location of that folder is defined on the `config.php` file.

**Comment by iskono** [comment]
i know , it uploads but gives broken link , ill check it again but all i can say is thanks for re working again on the CMS .
lets make it #1 world wide CMS
